#!/bin/sh

TEMPLATE_FOLDER="public-templates"
TARGET_FOLDER="public"


template_files=$(ls "$TEMPLATE_FOLDER")

for template_file in $template_files; do
  template_file_contents=$(cat "$TEMPLATE_FOLDER/$template_file")

  integrity_checks=$(grep -o -E "%%INTEGRITY:[a-zA-Z0-9_.-]+%%" "$TEMPLATE_FOLDER/$template_file")
  for integrity_check in $integrity_checks; do
    integrity_check_file_name=$(printf "%s" "$integrity_check" | cut -c "13-$((${#integrity_check}-2))")

    integrity_sha512=$(openssl dgst -sha512 "$TARGET_FOLDER/$integrity_check_file_name" | tail -c 128 | xxd -r -p | base64)
    integrity_check_string="sha512-$integrity_sha512"
    template_file_contents=$(echo "$template_file_contents" | sed "s#$integrity_check#$integrity_check_string#")
  done

  echo "$template_file_contents" > "$TARGET_FOLDER/$template_file"
done