#:schema node_modules/wrangler/config-schema.json
name = "khaopiak"
main = "src/index.ts"
compatibility_date = "2024-12-18"

# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Worker, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
# [placement]
# mode = "smart"

# Bind a Queue producer. Use this binding to schedule an arbitrary task that may be processed later by a Queue consumer.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#queues
[[queues.producers]]
binding = "CLEANUP_QUEUE"
queue = "khaopiak"

# Bind a Queue consumer. Queue Consumers can retrieve tasks scheduled by Producers to act on them.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#queues
[[queues.consumers]]
queue = "khaopiak"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#r2-buckets
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "khaopiak"
# This project uses Cloudflare Queues, which this project does not support.
#preview_bucket_name = "khaopiak-preview"

[assets]
directory = "./public/"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "none"

[build]
command = "./build.sh"
watch_dir = ['src', 'build.sh', 'public-templates']

[limits]
cpu_ms = 10